//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFapi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFapi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;static&quot;: {
        ///    &quot;release&quot;: &quot;Release&quot;,
        ///    &quot;all-groups&quot;: &quot;All Groups&quot;
        ///  },
        ///  &quot;error&quot;: {
        ///    &quot;authentication&quot;: &quot;Invalid authentication. Access denied.&quot;,
        ///    &quot;create&quot;: &quot;No record has been created. Please review your input.&quot;,
        ///    &quot;delete&quot;: &quot;No record has been deleted. Please review your selection.&quot;,
        ///    &quot;duplicate&quot;: &quot;No record has been created. A duplicate record already exists. Please review your input.&quot;,
        ///    &quot;exception&quot;: &quot;An unexpected error has occurred. Please seek technical support.&quot;,
        ///    &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;static&quot;: {
        ///    &quot;release&quot;: &quot;Eisiúint &quot;,
        ///    &quot;all-groups&quot;: &quot;Gach grúpa&quot;
        ///  },
        ///  &quot;error&quot;: {
        ///    &quot;authentication&quot;: &quot;Fíordheimhniú neamhbhailí. Níl cead isteach.&quot;,
        ///    &quot;create&quot;: &quot;Níor cruthaíodh taifead. Athbhreithnigh an méid a chuir tú isteach.&quot;,
        ///    &quot;delete&quot;: &quot;Níor scriosadh taifead. Athbhreithnigh an rogha a rinne tú.&quot;,
        ///    &quot;duplicate&quot;: &quot;Níor cruthaíodh taifead. Tá taifead dúblach ann cheana. Athbhreithnigh an méid a chuir tú isteach.&quot;,
        ///    &quot;exception&quot;: &quot;Tharla earráid neamhthuartha. Iarr tacaí [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ga {
            get {
                return ResourceManager.GetString("ga", resourceCulture);
            }
        }
    }
}
